### ISSUE TITLE
Blender

### ISSUE THREAD

**Issue by Almightynnanyi** [adroitwhiz/after-effects-to-blender-export#12]
Blender is not able to read the Json file from After effect

**Comment by adroitwhiz** [comment]
When you press the button to create an issue, there is a template that you should fill out:
![image](https://github.com/adroitwhiz/after-effects-to-blender-export/assets/25993062/3a37a030-b774-4763-ae1d-dd380bc0e895)
This template is there because I cannot read your mind or look at your screen, and do not know anything about the file you're having trouble with, your version of Blender, or the error message you're getting.

In order to actually solve the issue, I need:
1. The error message that Blender gives you
2. If possible, the .json file that causes Blender to error out
3. The version of Blender you're using

**Comment by adroitwhiz** [comment]
No actionable information; closing
